fix: resolve strategy-tests test failures
strategy-tests relies on rs-dpp; the usage of create_data_contract_create_transition requires features "client" and "state-transitions"

these weren't present; add them to Cargo.toml

introduced in PR 1729

```
> cargo t

error[E0599]: no method named `create_data_contract_create_transition` found for enum `DataContractFactory` in the current scope
    --> packages/strategy-tests/src/lib.rs:1186:34
     |
1185 |   ...                   let transition = match contract_factory
     |  ______________________________________________-
1186 | | ...                       .create_data_contract_create_transition(created_data_contract)
     | |                           -^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `DataContractFactory`
     | |___________________________|
     |
```